version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.18.1
    steps: 
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
      - run:
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules
      - run:
          command: npm test
          